export const VIETNAMESE_BANKS = [
     'Vietcombank - BIDV',
     'VietinBank',
     'BIDV',
     'Agribank',
     'Techcombank',
     'MB Bank',
     'VPBank',
     'ACB',
     'Sacombank',
     'VIB',
     'HDBank',
     'TPBank',
     'SHB',
     'SeABank',
     'OCB',
     'MSB',
     'VietCapital Bank',
     'Nam A Bank',
     'Bac A Bank',
     'Cake by VPBank',
     'Timo by VPBank',
     'TNEX',
] as const
